Repository Devcourse-BE6-8-3-Team10/Backend, pull requests merged in 2025-08, with the labels that each got.

#11 Feat#5 Chat관련 테스트 코드 작성
  src/test/java/com/back/domain/chat/chat/controller/ChatRestControllerTest.java
  src/test/java/com/back/domain/chat/chat/dto/MessageDtoTest.java
  src/test/java/com/back/domain/chat/chat/entity/ChatEntityTest.java
  src/test/java/com/back/domain/chat/chat/repository/ChatRepositoryTest.java
  src/test/java/com/back/domain/chat/chat/service/ChatServiceTest.java
Labels: feat

#21 [refactor] Trade Entity @Getter 제거 후 직접 구현
  src/main/java/com/back/domain/trade/entity/Trade.java
Labels: refactor

#28 [refactor] chat관련 엔티티 롬복 getter지우고 코드로 명시
  src/main/kotlin/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/kotlin/com/back/domain/chat/chat/entity/Message.java
  src/main/kotlin/com/back/domain/chat/chat/entity/RoomParticipant.java
Labels: refactor

#34 [refactor] TradeDto Kotlin 전환
  src/main/kotlin/com/back/domain/trade/dto/TradeDto.java
  src/main/kotlin/com/back/domain/trade/dto/TradeDto.kt
  src/test/kotlin/com/back/domain/trade/controller/AdmTradeControllerTest.java
  src/test/kotlin/com/back/domain/trade/controller/TradeControllerTest.java
Labels: refactor

#47 Refactor#44 Service 코틀린으로 교체
  src/main/kotlin/com/back/domain/chat/chat/entity/Message.java
  src/main/kotlin/com/back/domain/chat/chat/entity/RoomParticipant.java
  src/main/kotlin/com/back/domain/chat/chat/service/ChatService.java
  src/main/kotlin/com/back/domain/chat/chat/service/ChatService.kt
  src/test/kotlin/com/back/domain/chat/chat/service/ChatServiceTest.java
Labels: refactor

#52 Refactor#10 FileUploadDto Kotlin 전환 외
  src/main/kotlin/com/back/domain/files/files/dto/FileUploadResponseDto.java
  src/main/kotlin/com/back/domain/files/files/dto/FileUploadResponseDto.kt
  src/main/kotlin/com/back/domain/files/files/entity/Files.java
  src/main/kotlin/com/back/domain/files/files/repository/FilesRepository.java
  src/main/kotlin/com/back/domain/files/files/service/AsyncFileService.java
  src/main/kotlin/com/back/domain/files/files/service/CloudFileStorageService.java
  src/main/kotlin/com/back/domain/files/files/service/FileStorageService.java
  src/main/kotlin/com/back/domain/files/files/service/FilesService.java
  src/main/kotlin/com/back/domain/files/files/service/LocalFileStorageService.java
  src/main/kotlin/com/back/domain/member/service/MemberService.java
  src/main/kotlin/com/back/global/init/PostDataInitializer.java
Labels: refactor

#33 [Refactor] PostDetailDTO, PostRequest DTO, PostList DTO 코틀린 변경#3
  src/main/kotlin/com/back/domain/files/files/entity/Files.java
  src/main/kotlin/com/back/domain/post/controller/PostController.java
  src/main/kotlin/com/back/domain/post/dto/PostDetailDTO.java
  src/main/kotlin/com/back/domain/post/dto/PostDetailDTO.kt
  src/main/kotlin/com/back/domain/post/dto/PostListDTO.java
  src/main/kotlin/com/back/domain/post/dto/PostListDTO.kt
  src/main/kotlin/com/back/domain/post/dto/PostRequestDTO.java
  src/main/kotlin/com/back/domain/post/dto/PostRequestDTO.kt
  src/main/kotlin/com/back/domain/post/service/PostService.java
  src/test/kotlin/com/back/domain/post/dto/PostDtoTest.kt
Labels: refactor

#59 [refactor] TradeRepository Kotlin 변환
  src/main/kotlin/com/back/domain/trade/repository/TradeRepository.java
  src/main/kotlin/com/back/domain/trade/repository/TradeRepository.kt
  src/main/kotlin/com/back/domain/trade/service/TradeService.kt
Labels: refactor

#61 Refactor#10 : fileUrl 중복 삭제
  src/main/kotlin/com/back/domain/files/files/entity/Files.java
Labels: refactor

#64 Refactor#63: FilesRepository.kt로 전환
  src/main/kotlin/com/back/domain/files/files/repository/FilesRepository.java
  src/main/kotlin/com/back/domain/files/files/repository/FilesRepository.kt
Labels: refactor

#66 [refactor] 거래 컨트롤러 Kotlin 변환
  src/main/kotlin/com/back/domain/trade/controller/AdmTradeController.java
  src/main/kotlin/com/back/domain/trade/controller/AdmTradeController.kt
  src/main/kotlin/com/back/domain/trade/controller/TradeController.java
  src/main/kotlin/com/back/domain/trade/controller/TradeController.kt
Labels: refactor

#69 Refactor#65 : Files관련 Service로직 Kotlin변환
  src/main/kotlin/com/back/domain/files/files/entity/Files.java
  src/main/kotlin/com/back/domain/files/files/service/AsyncFileService.java
  src/main/kotlin/com/back/domain/files/files/service/AsyncFileService.kt
  src/main/kotlin/com/back/domain/files/files/service/CloudFileStorageService.java
  src/main/kotlin/com/back/domain/files/files/service/CloudFileStorageService.kt
  src/main/kotlin/com/back/domain/files/files/service/FileStorageService.java
  src/main/kotlin/com/back/domain/files/files/service/FileStorageService.kt
  src/main/kotlin/com/back/domain/files/files/service/FilesService.java
  src/main/kotlin/com/back/domain/files/files/service/FilesService.kt
  src/main/kotlin/com/back/domain/files/files/service/LocalFileStorageService.java
  src/main/kotlin/com/back/domain/files/files/service/LocalFileStorageService.kt
Labels: refactor

#76 Refactor#57 Chat Entity수정
  src/main/kotlin/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/kotlin/com/back/domain/chat/chat/entity/ChatRoom.kt
  src/main/kotlin/com/back/domain/chat/chat/entity/Message.java
  src/main/kotlin/com/back/domain/chat/chat/entity/Message.kt
  src/main/kotlin/com/back/domain/chat/chat/entity/RoomParticipant.java
  src/main/kotlin/com/back/domain/chat/chat/entity/RoomParticipant.kt
  src/main/kotlin/com/back/domain/chat/chat/repository/MessageRepository.kt
  src/main/kotlin/com/back/domain/chat/chat/service/ChatService.kt
  src/main/kotlin/com/back/global/init/ChatDataInitializer.java
  src/main/kotlin/com/back/global/init/ChatDataInitializer.kt
  src/test/kotlin/com/back/domain/chat/chat/entity/ChatEntityTest.java
  src/test/kotlin/com/back/domain/chat/chat/entity/ChatEntityTest.kt
  src/test/kotlin/com/back/domain/chat/chat/repository/ChatRepositoryTest.java
  src/test/kotlin/com/back/domain/chat/chat/service/ChatServiceTest.java
  src/test/kotlin/com/back/domain/chat/chat/service/ChatServiceTest.kt
Labels: refactor

#72 Refactor#71 : Files관련 Controller, Kotlin변환
  src/main/kotlin/com/back/domain/files/files/controller/AdminFilesController.java
  src/main/kotlin/com/back/domain/files/files/controller/AdminFilesController.kt
  src/main/kotlin/com/back/domain/files/files/controller/FileDownloadController.java
  src/main/kotlin/com/back/domain/files/files/controller/FileDownloadController.kt
  src/main/kotlin/com/back/domain/files/files/controller/FilesController.java
  src/main/kotlin/com/back/domain/files/files/controller/FilesController.kt
Labels: refactor

#79 Refactor#78 redis 폴더 코틀린으로 교체
  src/main/kotlin/com/back/domain/chat/redis/listener/RedisMessageSubscriber.java
  src/main/kotlin/com/back/domain/chat/redis/listener/RedisMessageSubscriber.kt
  src/main/kotlin/com/back/domain/chat/redis/service/RedisMessageService.java
  src/main/kotlin/com/back/domain/chat/redis/service/RedisMessageService.kt
  src/test/kotlin/com/back/domain/chat/chat/service/ChatServiceTest.kt
Labels: refactor

#85 [fix] Admin이 Member 정보(이름+상태) 변경 실패 수정
  src/main/kotlin/com/back/domain/admin/service/AdminService.java
  src/main/kotlin/com/back/domain/member/entity/Member.java
  src/test/kotlin/com/back/domain/admin/controller/AdminControllerTest.java
Labels: fix
